In [49]:
import pandas as pd
df = pd.read_csv(r"C:\Users\rahul\OneDrive\Documents\shopping_behavior.csv")

In [50]:
df.head(3)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                                                                                                                                                                                                                                                                                                          Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                                                                                                          --------------  -----
 0   Customer ID                                                                                                                                                                                                                                                                                                     3900 non-null   int64
 1   Age                                                                                                                                                                                                                                                                                                             3900 non-null   int64
 2   Gender                                                                                                                                                                                                                                                                                                          3900 non-null   object
 3   Item Purchased                                                                                                                                                                                                                                                                                                  3900 non-null   object
 4   Category                                                                                                                                                                                                                                                                                                        3900 non-null   object
 5   Purchase Amount (USD)                                                                                                                                                                                                                                                                                           3900 non-null   int64
 6   Location                                                                                                                                                                                                                                                                                                        3900 non-null   object
 7   Size                                                                                                                                                                                                                                                                                                            3900 non-null   object
 8   Color                                                                                                                                                                                                                                                                                                           3900 non-null   object
 9   Season                                                                                                                                                                                                                                                                                                          3900 non-null   object
 10  Review Rating                                                                                                                                                                                                                                                                                                   3900 non-null   float64
 11  Subscription Status                                                                                                                                                                                                                                                                                             3900 non-null   object
 12  Shipping Type                                                                                                                                                                                                                                                                                                   3900 non-null   object
 13  Discount Applied                                                                                                                                                                                                                                                                                                3900 non-null   object
 14  Promo Code Used                                                                                                                                                                                                                                                                                                 3900 non-null   object
 15  Previous Purchases                                                                                                                                                                                                                                                                                              3900 non-null   int64
 16  Payment Method                                                                                                                                                                                                                                                                                                  3900 non-null   object
 17  Frequency of Purchases                                                                                                                                                                                                                                                                                          3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [52]:
df.describe(include="all")

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3900.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.749949,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716223,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.700000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [53]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x:x.fillna(x.median()))
df.isnull().sum()

Customer ID                                                                                                                                                                                                                                                                                                       0
Age                                                                                                                                                                                                                                                                                                               0
Gender                                                                                                                                                                                                                                                                                                            0
Item Purchased                                                                                                                                                                                                                                                                                                    0
Category                                                                                                                                                                                                                                                                                                          0
Purchase Amount (USD)                                                                                                                                                                                                                                                                                             0
Location                                                                                                                                                                                                                                                                                                          0
Size                                                                                                                                                                                                                                                                                                              0
Color                                                                                                                                                                                                                                                                                                             0
Season                                                                                                                                                                                                                                                                                                            0
Review Rating                                                                                                                                                                                                                                                                                                     0
Subscription Status                                                                                                                                                                                                                                                                                               0
Shipping Type                                                                                                                                                                                                                                                                                                     0
Discount Applied                                                                                                                                                                                                                                                                                                  0
Promo Code Used                                                                                                                                                                                                                                                                                                   0
Previous Purchases                                                                                                                                                                                                                                                                                                0
Payment Method                                                                                                                                                                                                                                                                                                    0
Frequency of Purchases                                                                                                                                                                                                                                                                                            0
dtype: int64

In [54]:
df.columns

Index(['Customer ID                                                                                                                                                                                                                                                                                                   ',
       'Age', 'Gender', 'Item Purchased', 'Category', 'Purchase Amount (USD)',
       'Location', 'Size', 'Color', 'Season', 'Review Rating',
       'Subscription Status', 'Shipping Type', 'Discount Applied',
       'Promo Code Used', 'Previous Purchases', 'Payment Method',
       'Frequency of Purchases'],
      dtype='object')

In [55]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')

In [56]:
df.columns

Index(['customer_id___________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________',
       'age', 'gender', 'item_purchased', 'category', 'purchase_amount_(usd)',
       'location', 'size', 'color', 'season', 'review_rating',
       'subscription_status', 'shipping_type', 'discount_applied',
       'promo_code_used', 'previous_purchases', 'payment_method',
       'frequency_of_purchases'],
      dtype='object')

In [57]:
df = df.rename(columns = {'purchase_amount_(usd)' : 'purchase_amount'})

In [58]:
df.columns

Index(['customer_id___________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________',
       'age', 'gender', 'item_purchased', 'category', 'purchase_amount',
       'location', 'size', 'color', 'season', 'review_rating',
       'subscription_status', 'shipping_type', 'discount_applied',
       'promo_code_used', 'previous_purchases', 'payment_method',
       'frequency_of_purchases'],
      dtype='object')

In [59]:
#create a column age_group
labels = ['Young Adult','Adult','Middle-aged','Senior']
df['age_group'] = pd.qcut(df['age'],  q=4,labels = labels)

In [60]:
df[['age','age_group']].head(5)

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged

In [61]:
#create a column purchase_frequency_days
frequency_mapping = {
    'Fortnightly':14,
    'Weekly':7,
    'Monthly' :30,
    'Quarterly':90,
    'Bi-Weekly':14,
    'Annually':365,
    'Every 3 Months':90
}
df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [62]:
df[['purchase_frequency_days', 'frequency_of_purchases']].head(5)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually

In [63]:
df[['discount_applied','promo_code_used']].head(5)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes

In [64]:
df = df.drop('promo_code_used',axis=1)

In [65]:
df.columns

Index(['customer_id___________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________',
       'age', 'gender', 'item_purchased', 'category', 'purchase_amount',
       'location', 'size', 'color', 'season', 'review_rating',
       'subscription_status', 'shipping_type', 'discount_applied',
       'previous_purchases', 'payment_method', 'frequency_of_purchases',
       'age_group', 'purchase_frequency_days'],
      dtype='object')

In [66]:
pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in c:\users\rahul\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: pymysql in c:\users\rahul\anaconda3\lib\site-packages (1.2.0)
Requirement already satisfied: greenlet>=1 in c:\users\rahul\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\rahul\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [67]:
!pip install pymysql sqlalchemy

Requirement already satisfied: pymysql in c:\users\rahul\anaconda3\lib\site-packages (1.2.0)
Requirement already satisfied: sqlalchemy in c:\users\rahul\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\users\rahul\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\rahul\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)

In [68]:
import pandas as pd
from sqlalchemy import create_engine

In [ ]:
username = "root"
password = "1111"
host = "localhost"
port = "3306"
database = "customer_behaviour"

engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

In [70]:
connection = engine.connect()
print("Connected Successfully")
connection.close()

Connected Successfully

In [71]:
df = pd.read_sql("SELECT * FROM customer1", engine)
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [ ]:
df = pd.read_csv(r"C:\Users\rahul\Downloads\customer_shopping_behavior.csv")

df.to_sql(
    name="customer1",
    con=engine,
    if_exists="replace",
    index=False
)

print("Data Uploaded Successfully")

In [ ]:
! pip install mysql-connector-python

In [ ]:
import mysql.connector as sql

In [ ]:
conn = mysql.connector.connect(
    host = "localhost",
    user = "root",
    password = "1111",
    database = "customer_behaviour")
mycursor = conn.cursor()
print(conn)

In [ ]:
mycursor.execute("select * from customer1")
output = mycursor.fetchall()

for x in output:
    print(x)